# This is a basic workflow to help you get started with Actions

name: resumeWebsite CI/CD

# Controls when the action will run. 
on:
  push:
        branches: [ master ]
  pull_request:
        branches: [ master ]
        
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURERESUMECRED }}
          
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name resumewebsitepage -d '$web' -s .
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "portfoliowebsite" --name "https://greybeing.azureedge.net" --resource-group "Resume"
           
            # Azure logout 
    - name: logout
      run: |
            az logout
 
